server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-Resource-server
          uri: lb://auth-Resource-server
          predicates:
            - Path=/resourceServer1/**
        - id: auth-stock-client
          uri: lb://auth-stock-client
          predicates:
            - Path=/stockServiceClient/**
        - id: customer-Api
          uri: lb://customer-Api
          predicates:
            - Path=/customerDetails/**